import { GoogleGenAI, Type } from "@google/genai";
import { FlowStep } from "../types";

// Helper to generate a unique ID
const generateId = () => Math.random().toString(36).substr(2, 9);

export const generateRoutine = async (prompt: string): Promise<{ title: string; description: string; icon: string; steps: FlowStep[] }> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key is missing. Please set the API_KEY environment variable.");
  }

  const ai = new GoogleGenAI({ apiKey });

  const systemInstruction = `
    You are an expert productivity coach for the 'FlowStack' app. 
    Your goal is to create highly effective, scientifically backed habit stacks and deep work routines.
    
    Rules:
    1. Break down the routine into actionable, linear steps.
    2. Assign realistic durations (in seconds).
    3. Select a single emoji that best represents this routine as an 'icon'.
    4. Keep titles concise (under 5 words).
    5. Descriptions should be motivational.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Create a productivity routine for: "${prompt}".`,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING, description: "A catchy title for the routine" },
            description: { type: Type.STRING, description: "A short motivating description" },
            icon: { type: Type.STRING, description: "A single emoji representing the routine" },
            steps: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING },
                  duration: { type: Type.INTEGER, description: "Duration in seconds" },
                  description: { type: Type.STRING, description: "One sentence instruction" }
                },
                required: ["title", "duration"]
              }
            }
          },
          required: ["title", "description", "steps", "icon"]
        }
      }
    });

    const result = JSON.parse(response.text || "{}");
    
    // Enrich with IDs on the client side
    const stepsWithIds = result.steps?.map((step: any) => ({
      ...step,
      id: generateId()
    })) || [];

    return {
      title: result.title || "New Routine",
      description: result.description || "Generated by AI",
      icon: result.icon || "⚡",
      steps: stepsWithIds
    };

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw new Error("Failed to generate routine. Please try again.");
  }
};
